# Generated by Django 5.2.3 on 2025-06-25 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('c', 'C'), ('cpp', 'C++'), ('javascipt', 'Javascript'), ('java', 'Java'), ('go', 'Go'), ('ruby', 'Ruby'), ('rust', 'Rust')], default='python', max_length=50)),
                ('runtime', models.FloatField(blank=True, null=True)),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('TLE', 'TLE'), ('Runtime Error', 'Runtime Error'), ('Compilation Error', 'Compilation Error')], max_length=50)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField()),
                ('test_case_passed', models.IntegerField()),
                ('total_test_cases', models.IntegerField()),
                ('total_cases_failed', models.IntegerField()),
                ('error', models.TextField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission')),
            ],
        ),
    ]
